stages:
  - build
  - test
  - deploy



build_a:
  stage: build
  image: docker:20.10.10
  services:
      - docker:20.10.10-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER registry.gitlab.com --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE 