stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  image: docker:20.10.10
  services:
      - docker:20.10.10-dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER registry.gitlab.com --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE:v1" -f Dockerfile_front .
    - docker push "$CI_REGISTRY_IMAGE:v1" 

deploy_k8s:
  image: alpine
  stage: deploy
  script:
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo "$KUBE_CONFIG" >> config
    - mv config ~/.kube/
    - kubectl get pods