stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  image: docker:20.10.10
  services:
      - docker:20.10.10-dind
  script:
   - echo $DOCKER_REGISTRY_KEY | docker login -u $DOCKER_REGISTRY_USER registry-1.docker.io --password-stdin
    - docker build --pull -t "kevinsantiagorey/personalwebsite:v1" -f Dockerfile_front .
    - docker images
    - docker push kevinsantiagorey/personalwebsite:v1 

deploy_k8s:
  image: docker:20.10.10
  services:
      - docker:20.10.10-dind
  stage: deploy
  script:
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo "$KUBE_CONFIG" >> config
    - mv config ~/.kube/
    - echo $DOCKER_REGISTRY_KEY | docker login -u $DOCKER_REGISTRY_USER registry-1.docker.io --password-stdin
    - cd k8s/app && kubectl apply -f deployment.yml