FROM node as builderFront
ARG REGISTRY_KEY
RUN git clone https://gitlab+deploy-token-1692456:REGISTRY_KEY@gitlab.com/personalwebsite3/personalwebsite.git /home/html/

FROM nginx
COPY --from=builderFront /home/html/ /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]