apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpersonal-SNAPSHOT
spec:
  selector:
    matchLabels:
      app: blogpersonal-SNAPSHOT
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: version v1.2
      labels:
        app: blogpersonal-SNAPSHOT
    spec:
      containers:
      - name: blogpersonal-SNAPSHOT
        image: kevinsantiagorey/personalwebsite:SNAPSHOT
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 80
